name: T-TheTag
main: pl.timsixth.thetag.TheTagPlugin
version: '1.7.0'
description: The tag minigame
website: https://timsixth.pl/
api-version: 1.13
author: timsixth
depend:
  - T-MiniGameAPI
softdepend:
  - PlaceholderAPI
  - Multiverse-Core
commands:
  thetag:
  tta:
    aliases:
      - thetagadmin